name: tarea7_codelabs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  go_router: ^14.0.1
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  provider: ^6.1.2
  firebase_ui_auth: ^1.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
dependency_overrides:
  intl: ^0.17.0
flutter:
  uses-material-design: true
  assets:
    - assets/codelab.png